changelog:
  categories:
    - title: 🚀 Features
      labels:
        - epic
        - User Story
    - title: 🐛 Bug Fixes
      labels:
        - bug
    - title: 🛠️ Improvements
      labels:
        - refactoring
    - title: 📚 Documentation
      labels:
        - documentation
        - UI
        - research
    - title: 🔧 Other Changes
      labels:
        - Code execution system
        - test
        - backend
        - frontend
