[pytest]
pythonpath = src
testpaths = tests
# These two lines tell pytest to automatically handle async tests
asyncio_mode = auto
asyncio_default_test_loop_scope = function

filterwarnings =
    ignore::pydantic.PydanticDeprecatedSince20
    ignore::DeprecationWarning
    ignore:Unknown pytest.mark.asyncio